### ISSUE TITLE
Let's setup copy over files from handsfree-discourse

### ISSUE THREAD

**Issue by BrowseHandsfree** [BrowseHandsfree/discourse-webpack#1]
## Tasks
- [ ] Copy files from [handsfree-discourse](https://github.com/browsehandsfree/handsfree-discourse)
- [ ] Create a README.md

## Announce
Announce
- [ ] Tweet (mention Jeeliz and Discourse)
- [ ] Discourse
- [ ] Medium
- [ ] Instagram
- [ ] YouTube

## Topics/Blogs
- [ ] How to use handsfree-discourse
- [ ] How we made it
